from __future__ import annotations

from typing import Protocol

from vectorledger.models import Artifact, ArtifactState, Document, DocumentKey, Receipt


class LedgerStore(Protocol):
    async def initialize(self) -> None: ...

    async def close(self) -> None: ...

    async def upsert_document(self, document: Document) -> Document: ...

    async def get_document(self, key: DocumentKey) -> Document | None: ...

    async def list_documents(self) -> list[Document]: ...

    async def add_artifact(self, artifact: Artifact) -> Artifact: ...

    async def list_artifacts(self, key: DocumentKey) -> list[Artifact]: ...

    async def mark_artifacts(
        self, key: DocumentKey, target: str, state: ArtifactState, error: str | None = None
    ) -> None: ...

    async def save_receipt(self, receipt: Receipt) -> Receipt: ...

    async def get_receipt(self, receipt_id: str) -> Receipt | None: ...
